title: <p align="center"> Krishna Jinka </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/krishna-jinka/">LinkedIn</a> |
  <a href="https://github.com/krishnajinka">GitHub</a>
  
  <br>   
  Principal Software Architect @ GE Healthcare | Big Data, Cloud Development
  I am a Principal Software Architect at GE Healthcare, where I lead the design and development of scalable and secure cloud solutions for the healthcare industry. 
  I have over 17 years of experience in software engineering, spanning various domains such as NFV, SDN, ONAP, and bioinformatics.
  My core competencies include cloud development, DevOps, agile methodologies, project and release management, and performance analysis. 
  I have extensive hands-on experience in Java Spring Cloud, Kubernetes, Jenkins, Ansible, Python, and virtualization.
  I have also worked on ETSI-based NFV MANO implementation with RESTful services, OSS integration, OpenStack, and VNF. 
  I am passionate about solving complex problems, learning new technologies, and collaborating with diverse teams. 
  My goal is to deliver innovative and impactful solutions that improve the quality and accessibility of healthcare services.
  <br>
  </p>



theme: jekyll-theme-minimal
